### ISSUE TITLE
Error in:   AzElPolarPlot_comtypes.ipynb

### ISSUE THREAD

**Issue by elenzing** [AnalyticalGraphicsInc/STKCodeExamples#174]
COMError                                  Traceback (most recent call last)
C:\Users\HPZ620~1\AppData\Local\Temp/ipykernel_7984/280915811.py in <module>
     36 #Get all the access interval start and stop times
     37 accessReport = access.DataProviders.Item("Access Data").QueryInterface(STKObjects.IAgDataPrvInterval)
---> 38 accessIntervals = accessReport.ExecElements(scenario2.StartTime, scenario2.Stoptime, ["Access Number","Start Time", "Stop Time"])
     39 accessIntervals = list(accessIntervals.DataSets.ToArray())
     40 #Get Az El data for each access interval

COMError: (-2147417851, 'The server threw an exception.', (None, None, None, 0, None))

**Comment by arogersagi** [comment]
Accidental commit? Closing for now.

**Comment by arogersagi** [comment]
Hi there - this seems to be a problem with Python 3.8's compatibility with the comtypes library, which is documented in the comtypes repo [here](https://github.com/enthought/comtypes/issues/212). I would recommend trying this script again with Python 3.7 or creating a new script using the new [Python API](https://help.agi.com/stkdevkit/index.htm#python/pythonIntro.htm?TocPath=Development%2520Environments%257CSTK%2520Python%2520API%257C_____0).

**Comment by arogersagi** [comment]
Closing for now, will reopen if additional comments are added.
