### ISSUE TITLE
RunTimeWarning on RunLifeTimeAnalysis.py

### ISSUE THREAD

**Issue by RaphaellBG** [AnalyticalGraphicsInc/STKCodeExamples#205]
Hi! 

When attempting to run the script RunLifeTimeAnalysis.py, I get the error message: 

"RuntimeWarning: coroutine 'runTasks' was never awaited
with suppress(Exception): # Used to ignore the "RuntimeError: Cannot close a running event loop" due to running in Jupyter" 

So far, I've had no success while trying to debug the LifeTimeLib.py file provided. 

Would appreciate any help. Thank you!

**Comment by jpthompson212** [comment]
Hey, I'm looking into this and will get back to you soon!

**Comment by jpthompson212** [comment]
@RaphaellBG Would you be able to provide some more information about where you are seeing the error?  I just pulled a fresh copy of this and everything ran with no errors. 

Also could you specify what version of STK you are using?

**Comment by jpthompson212** [comment]
Closing this for now.  If you still have issues please let us know!
